goog.provide('cinemart.config');
cinemart.config.debug_QMARK_ = goog.DEBUG;
cinemart.config.powered_by = new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"src","src",-1651076051),"https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg",new cljs.core.Keyword(null,"alt","alt",-3214426),"tmdb",new cljs.core.Keyword(null,"href","href",-793805698),"https://www.themoviedb.org/"], null),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"src","src",-1651076051),"https://tailwindcss.com/_next/static/media/tailwindcss-mark.6ea76c3b72656960a6ae5ad8b85928d0.svg",new cljs.core.Keyword(null,"alt","alt",-3214426),"tailwind",new cljs.core.Keyword(null,"href","href",-793805698),"https://tailwindcss.com/"], null),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"src","src",-1651076051),"https://github.com/day8/re-frame/raw/master/docs/images/logo/re-frame-colour.png?raw=true",new cljs.core.Keyword(null,"alt","alt",-3214426),"re-frame",new cljs.core.Keyword(null,"href","href",-793805698),"https://day8.github.io/re-frame/"], null)], null);
cinemart.config.api_interceptor = (function (){var G__27257 = new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),"inject api key and append uri",new cljs.core.Keyword(null,"request","request",1772954723),(function (request){
var uri = new cljs.core.Keyword(null,"uri","uri",-774711847).cljs$core$IFn$_invoke$arity$1(request);
return cljs.core.assoc_in(cljs.core.assoc_in(request,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"params","params",710516235),new cljs.core.Keyword(null,"api_key","api_key",-1567758224)], null),cinemart.env.api_key),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"uri","uri",-774711847)], null),["https://api.themoviedb.org/3",cljs.core.str.cljs$core$IFn$_invoke$arity$1(uri)].join(''));
})], null);
return (ajax.core.to_interceptor.cljs$core$IFn$_invoke$arity$1 ? ajax.core.to_interceptor.cljs$core$IFn$_invoke$arity$1(G__27257) : ajax.core.to_interceptor.call(null,G__27257));
})();

//# sourceMappingURL=cinemart.config.js.map
